version: '3'

services:
  app: # NODEJS
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./
    tty: true
    ports:
      - "3000:3000"
networks:
  node-network:
    driver: bridge